from pathlib import Path

path = Path('src/App.tsx')
text = path.read_text()

def rep(old: str, new: str, label: str):
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected 1 match, found {count}')
    text = text.replace(old, new, 1)

rep("type BackgroundDynamics = 'empty-still' | 'casual-indifferent' | 'busy-motion';", "type BackgroundDynamics = 'empty' | 'casual' | 'busy';\ntype FramingImperfection = 'perfect' | 'dutch-angle' | 'awkward-crop';", 'types')
rep("interface SceneState {\n  referenceImageId: string | null;", "interface SceneState {\n  referenceImageId: string | null;\n  hasGlasses: boolean;", 'hasGlasses')
rep("  cameraAngle: CameraAngle;\n  pose: string;", "  cameraAngle: CameraAngle;\n  framingImperfection: FramingImperfection;\n  useDigitalZoom: boolean;\n  pose: string;", 'camera fields')
rep("  flashEffects: string;\n}", "  flashEffects: string;\n  framingImperfectionDetails: string;\n}", 'derived field')
rep("  backgroundDynamics: string;\n}", "  backgroundDynamics: string;\n  negativePrompt: string;\n}", 'semantic field')
rep("const IDENTITY_LOCK = `Preserve exact facial identity from the reference image. 193cm height, 83kg weight, tall lean-athletic male build. Dark rectangular eyeglasses visible in reference MUST be worn. DO NOT alter facial proportions, head geometry, hairline, or natural hair density. DO NOT artificially beautify, de-age, or smooth skin. Preserve natural facial asymmetry and existing beard/moustache growth pattern.`;", "const IDENTITY_LOCK = `Preserve exact facial identity from the reference image. 193cm height, 83kg weight, tall lean-athletic male build. DO NOT alter facial proportions, head geometry, hairline, or natural hair density. DO NOT artificially beautify, de-age, or smooth skin. Preserve natural facial asymmetry and existing beard/moustache growth pattern.`;", 'identity')

text = text.replace("'empty-still'", "'empty'").replace("'casual-indifferent'", "'casual'").replace("'busy-motion'", "'busy'")

rep("  if (isDay && newState.flashMode === 'direct-flash') newState.flashMode = 'no-flash';\n\n  return newState;", "  if (isDay && newState.flashMode === 'direct-flash') newState.flashMode = 'no-flash';\n  if (!newState.hasGlasses && newState.handProp === 'adjusting-glasses') newState.handProp = 'none';\n\n  return newState;", 'conflict')
rep("    facialHairDetails: '',\n    flashEffects: ''", "    facialHairDetails: '',\n    flashEffects: '',\n    framingImperfectionDetails: 'balanced intentional framing with natural smartphone headroom'", 'derived default')
rep("  derived.shadowBehavior += ', deep ambient occlusion in clothing folds and under jawline, hard physically accurate contact shadow grounding the subject';\n", "  derived.shadowBehavior += ', deep ambient occlusion in clothing folds and under jawline, hard physically accurate contact shadow grounding the subject';\n\n  if (state.hasGlasses) {\n    derived.lensEffects += ', subtle optical refraction through the thicker edge of the glasses lens causing a minute natural cheekbone displacement, microscopic smartphone-screen reflection visible in one lens when angle and lighting permit';\n    derived.realismConstraints.push('PRESERVE the exact eyeglass frame shape, size, color, fit, lens geometry, and temple position from the reference image', 'eyeglasses must show realistic bridge contact and temple pressure with no warped or floating frames');\n  }\n", 'eyewear physics')
rep("      derived.skinResponse += ', subtle realistic colored reflection from dashboard lights on the lower face and eyeglasses';", "      derived.skinResponse += ', subtle realistic colored reflection from dashboard lights on the lower face';\n      if (state.hasGlasses) derived.lensEffects += ', faint dashboard and streetlight reflections on the eyeglass lenses';", 'car eyewear')
rep("    derived.shadowBehavior = 'Strong, sharp, short shadows directly beneath nose, chin, and eyeglasses frames. Deep ambient occlusion under headwear or hair.';", "    derived.shadowBehavior = 'Strong, sharp, short shadows directly beneath nose and chin. Deep ambient occlusion under headwear or hair.';\n    if (state.hasGlasses) derived.shadowBehavior += ' Small physically consistent frame shadows from the eyeglasses fall onto the upper cheeks.';", 'midday eyewear')
rep("    derived.contactPhysics.push('one arm clearly extended holding the camera causing slight shoulder elevation and torso compensation');", "    derived.contactPhysics.push('one arm clearly extended holding the camera with asymmetrical shoulder elevation, visible clavicle tension on the camera-holding side, subtle torso compensation, and the clothing collar shifted slightly by the raised arm');", 'selfie anatomy')
rep("  } else {\n    derived.cameraDistance = 'third-person candid distance (approx 1.5 - 3 meters)';\n    derived.realismConstraints.push('candid framing without selfie-arm mechanics, natural depth of field');\n    derived.lensEffects = 'smartphone main camera aesthetic, 35mm equivalent focal length, natural f/1.8 depth of field with gradual, non-artificial background blur. ' + derived.lensEffects;\n  }\n\n  // --- 6. Physics & Contact Logic ---", "  } else {\n    derived.cameraDistance = 'third-person candid distance (approx 1.5 - 3 meters)';\n    derived.realismConstraints.push('candid framing without selfie-arm mechanics, natural depth of field');\n    derived.lensEffects = 'smartphone main camera aesthetic, 35mm equivalent focal length, natural f/1.8 depth of field with gradual, non-artificial background blur. ' + derived.lensEffects;\n    if (state.useDigitalZoom) {\n      derived.lensEffects = 'smartphone digital zoom artifacts from an in-sensor crop, slight watercolor-like upscaling on fine textures such as hair and fabric fibers, loss of micro-contrast, mild edge sharpening halos. ' + derived.lensEffects;\n      derived.realismConstraints.push('digital zoom must reduce fine-detail fidelity rather than creating artificial optical bokeh');\n    }\n  }\n\n  if (state.framingImperfection === 'dutch-angle') {\n    derived.framingImperfectionDetails = 'unintentional slight Dutch angle of roughly 2-5 degrees, imperfect horizon, casual amateur phone handling';\n  } else if (state.framingImperfection === 'awkward-crop') {\n    derived.framingImperfectionDetails = 'awkward amateur crop with slightly tight or uneven headroom and imperfect centering, while keeping the eyes, chin, and essential facial identity readable';\n  } else {\n    derived.framingImperfectionDetails = 'balanced intentional framing with natural smartphone headroom and no artificial studio-perfect symmetry';\n  }\n\n  // --- 6. Physics & Contact Logic ---", 'framing zoom')
rep("  if (state.handProp !== 'none') {", "  if (state.handProp !== 'none' && (state.handProp !== 'adjusting-glasses' || state.hasGlasses)) {", 'prop guard')

rep("    captureMechanics = `Smartphone front-camera selfie. Framing: ${state.framing}. Camera angle: ${state.cameraAngle}. Gaze: ${gaze?.prompt}. ${derived.contactPhysics.find(p => p.includes('arm')) || ''}`;", "    captureMechanics = `Smartphone front-camera selfie. Framing: ${state.framing}. Camera angle: ${state.cameraAngle}. Distance: ${derived.cameraDistance}. Amateur framing behavior: ${derived.framingImperfectionDetails}. Gaze: ${gaze?.prompt}. ${derived.contactPhysics.find(p => p.includes('arm')) || ''}`;", 'front mechanics')
rep("    captureMechanics = `Smartphone mirror selfie. Framing: ${state.framing}. Gaze: ${gaze?.prompt}. ${derived.reflectionRules.join('. ')}`;", "    captureMechanics = `Smartphone mirror selfie. Framing: ${state.framing}. Distance: ${derived.cameraDistance}. Framing behavior: ${derived.framingImperfectionDetails}. Gaze: ${gaze?.prompt}. ${derived.reflectionRules.join('. ')}`;", 'mirror mechanics')
rep("    captureMechanics = `Third-person candid photograph. Framing: ${state.framing}. Camera angle: ${state.cameraAngle}. Gaze: ${gaze?.prompt}.`;", "    captureMechanics = `Third-person candid photograph. Framing: ${state.framing}. Camera angle: ${state.cameraAngle}. Distance: ${derived.cameraDistance}. Framing behavior: ${derived.framingImperfectionDetails}. Gaze: ${gaze?.prompt}.`;", 'candid mechanics')
rep("    identity: IDENTITY_LOCK,", "    identity: state.hasGlasses\n      ? `${IDENTITY_LOCK} The subject wears eyeglasses in the reference image: STRICTLY preserve the exact same frame shape, color, proportions, lens geometry, bridge fit, and temple position.`\n      : IDENTITY_LOCK,", 'semantic identity')
rep("    backgroundDynamics: backgroundDynamics.description\n  };", "    backgroundDynamics: backgroundDynamics.description,\n    negativePrompt: state.backgroundDynamics === 'empty'\n      ? 'background people, crowd, background people staring at camera, posed background characters'\n      : 'background people staring at camera, posed background characters, generic stock-photo crowd, duplicated people, cloned faces'\n  };", 'negative semantic')
rep("  const identityBlock = `SUBJECT: A 193cm tall, 83kg lean-athletic Saudi male. MUST preserve exact facial identity, natural facial asymmetry, and existing beard/moustache pattern from the reference image. Dark rectangular eyeglasses MUST be worn. DO NOT alter facial proportions or hairline. Facial hair: ${semantic.facialHair}.`;", "  const identityBlock = `SUBJECT & IDENTITY: ${semantic.identity} Facial hair: ${semantic.facialHair}.`;", 'prompt identity')
rep("  const textureBlock = `TEXTURE DETAILS: ${semantic.skinResponse}. Hair: ${semantic.hair}. Hand prop: ${semantic.handProp}.`;", "  const textureBlock = `TEXTURE DETAILS: ${semantic.skinResponse}. Hair: ${semantic.hair}. Hand prop: ${semantic.handProp}.`;\n  const negativeBlock = `NEGATIVE PROMPT: ${semantic.negativePrompt}.`;", 'negative block')
rep("- NO perfect symmetry, NO waxy skin, NO floating objects, NO impossible lighting.`;", "- NO perfect symmetry, NO waxy skin, NO floating objects, NO impossible lighting.\n\n${negativeBlock}`;", 'chatgpt negative')
rep("The image features a 193cm tall, 83kg lean-athletic Saudi male wearing dark rectangular eyeglasses, preserving exact natural facial asymmetry, skin texture, and hairline from the reference. Facial hair: ${semantic.facialHair}. He is wearing: ${semantic.outfit}. The fabric shows realistic physical behavior: ${semantic.outfitPhysics}.", "The image features this subject identity: ${semantic.identity} Facial hair: ${semantic.facialHair}. He is wearing: ${semantic.outfit}. The fabric shows realistic physical behavior: ${semantic.outfitPhysics}.", 'gemini identity')
rep("The image must strictly adhere to these realism constraints: ${semantic.styleConstraints}. Avoid any CGI, 3D render aesthetics, studio lighting, or artificial smoothing. Embrace authentic, unedited photographic imperfections.`;", "The image must strictly adhere to these realism constraints: ${semantic.styleConstraints}. Avoid any CGI, 3D render aesthetics, studio lighting, or artificial smoothing. Embrace authentic, unedited photographic imperfections.\n\n${negativeBlock}`;", 'gemini negative')

rep("  referenceImageId: '1000236308.png', sceneFamily: null, subScene: '', activity: '', captureType: 'front-selfie', framing: 'chest-up', cameraAngle: 'eye-level', pose: '', outfitId: 'mil3', hairStyle: 'h2', expression: 'e1', timeOfDay: 'midday', lightingMode: '', environmentRealism: 'رسمية ومنظمة', realismStyle: 'anti-ai-raw', lensCondition: 'modern-iphone', clothingCondition: 'crisp', atmosphericCondition: 'neutral', foregroundObstruction: 'clean', gazeDirection: 'at-camera', handProp: 'none', facialHairState: '3-day-stubble', flashMode: 'no-flash', backgroundDynamics: 'empty'", "  referenceImageId: '1000236308.png', hasGlasses: false, sceneFamily: null, subScene: '', activity: '', captureType: 'front-selfie', framing: 'chest-up', cameraAngle: 'eye-level', framingImperfection: 'perfect', useDigitalZoom: false, pose: '', outfitId: 'mil3', hairStyle: 'h2', expression: 'e1', timeOfDay: 'midday', lightingMode: '', environmentRealism: 'رسمية ومنظمة', realismStyle: 'anti-ai-raw', lensCondition: 'modern-iphone', clothingCondition: 'crisp', atmosphericCondition: 'neutral', foregroundObstruction: 'clean', gazeDirection: 'at-camera', handProp: 'none', facialHairState: '3-day-stubble', flashMode: 'no-flash', backgroundDynamics: 'empty'", 'default state')
rep("        if (savedState) setState({ ...DEFAULT_STATE, ...JSON.parse(savedState) });", "        if (savedState) {\n          const parsedState = JSON.parse(savedState);\n          if (parsedState.backgroundDynamics === 'empty-still') parsedState.backgroundDynamics = 'empty';\n          if (parsedState.backgroundDynamics === 'casual-indifferent') parsedState.backgroundDynamics = 'casual';\n          if (parsedState.backgroundDynamics === 'busy-motion') parsedState.backgroundDynamics = 'busy';\n          setState({ ...DEFAULT_STATE, ...parsedState });\n        }", 'migration')
rep("  const activeFamily = state.sceneFamily ? SCENE_FAMILIES[state.sceneFamily] : null;\n  const filteredOutfits = OUTFITS.filter(o => state.sceneFamily ? o.category.includes(state.sceneFamily) : true);", "  const activeFamily = state.sceneFamily ? SCENE_FAMILIES[state.sceneFamily] : null;", 'filtered outfits')
rep("    setState({ ...state, sceneFamily: familyId, subScene: family.subScenes[0], activity: family.activities[0], pose: family.poses[0], lightingMode: family.allowedLighting[0], environmentRealism: family.environmentRealism[0], outfitId: OUTFITS.find(o => o.category.includes(familyId))?.id || 'cas1' });", "    setState({ ...state, sceneFamily: familyId, subScene: family.subScenes[0], activity: family.activities[0], pose: family.poses[0], lightingMode: family.allowedLighting[0], environmentRealism: family.environmentRealism[0] });", 'scene outfit')
rep("    const availableOutfits = OUTFITS.filter(o => o.category.includes(randomFamilyId));\n", "", 'smart outfits')
text = text.replace(", outfitId: availableOutfits[Math.floor(Math.random() * availableOutfits.length)]?.id || availableOutfits[0]?.id || 'bed1'", "")
rep("  const handleVibePreset = (preset: VibePreset) => setState({ ...state, ...preset.state });", "  const handleVibePreset = (preset: VibePreset) => setState({ ...state, ...preset.state, outfitId: state.outfitId });", 'preset outfit')

rep("          )}\n        </div>\n\n        <div className=\"px-5 py-2\">", "          )}\n          <label className=\"mt-3 flex items-center justify-between gap-3 bg-[var(--bg-card)] border border-[var(--border)] rounded-xl px-4 py-3 cursor-pointer\">\n            <div>\n              <span className=\"text-sm font-medium block\">هل الشخص يرتدي نظارة؟</span>\n              <span className=\"text-[10px] text-[var(--text-muted)]\">يُستخدم لتثبيت النظارة وفيزياء العدسات فقط عند التفعيل</span>\n            </div>\n            <input type=\"checkbox\" checked={state.hasGlasses} onChange={e => setState({...state, hasGlasses: e.target.checked})} className=\"w-5 h-5 accent-[var(--accent)] shrink-0\" />\n          </label>\n        </div>\n\n        <div className=\"px-5 py-2\">", 'eyewear UI')

rep("                  </select>\n                </section>\n\n                <section className=\"bg-[var(--bg-card)] p-4 rounded-2xl border border-[var(--border)]\">\n                   <h3 className=\"font-medium mb-3 text-sm text-[var(--text-muted)]\">إعدادات الكاميرا والكادر</h3>", "                  </select>\n                </section>\n\n                <section className=\"bg-[var(--bg-card)] p-4 rounded-2xl border border-[var(--border)]\">\n                  <h3 className=\"font-medium mb-3 text-sm text-[var(--text-muted)]\">الخلفية والبيئة</h3>\n                  <label className=\"text-[11px] text-[var(--text-muted)] block mb-1\">حركة الخلفية</label>\n                  <select value={state.backgroundDynamics} onChange={e => setState({...state, backgroundDynamics: e.target.value as BackgroundDynamics})} className=\"w-full bg-[var(--bg-main)] border border-[var(--border)] rounded-xl px-3 py-2.5 text-sm appearance-none focus-ring\">\n                    <option value=\"empty\">فارغة وهادئة</option>\n                    <option value=\"casual\">عابرون غير مبالين</option>\n                    <option value=\"busy\">مزدحمة وحركية</option>\n                  </select>\n                </section>\n\n                <section className=\"bg-[var(--bg-card)] p-4 rounded-2xl border border-[var(--border)]\">\n                   <h3 className=\"font-medium mb-3 text-sm text-[var(--text-muted)]\">إعدادات الكاميرا والكادر</h3>", 'environment UI')

rep("                  </select>\n                </section>\n\n                <section>\n                   <div className=\"flex justify-between items-center mb-3\">\n                     <h3 className=\"font-medium\">الملابس والشخصية</h3>", "                  </select>\n                  <div className=\"mt-3\">\n                    <label className=\"text-[11px] text-[var(--text-muted)] block mb-1\">عدم مثالية التأطير</label>\n                    <select value={state.framingImperfection} onChange={e => setState({...state, framingImperfection: e.target.value as FramingImperfection})} className=\"w-full bg-[var(--bg-main)] border border-[var(--border)] rounded-xl px-4 py-2.5 text-sm appearance-none focus-ring\">\n                      <option value=\"perfect\">تأطير مثالي</option>\n                      <option value=\"dutch-angle\">ميلان عشوائي</option>\n                      <option value=\"awkward-crop\">تأطير سيء للرأس</option>\n                    </select>\n                  </div>\n                  {state.captureType === 'third-person-candid' && (\n                    <label className=\"mt-3 flex items-center justify-between gap-3 bg-black/10 border border-[var(--border)] rounded-xl px-3 py-2.5 cursor-pointer\">\n                      <span className=\"text-xs\">استخدام تقريب رقمي للهاتف</span>\n                      <input type=\"checkbox\" checked={state.useDigitalZoom} onChange={e => setState({...state, useDigitalZoom: e.target.checked})} className=\"w-5 h-5 accent-[var(--accent)]\" />\n                    </label>\n                  )}\n                </section>\n\n                <section>\n                   <div className=\"flex justify-between items-center mb-3\">\n                     <h3 className=\"font-medium\">الملابس والشخصية</h3>", 'camera UI')

rep("                   <div className=\"flex justify-between items-center mb-3\">\n                     <h3 className=\"font-medium\">الملابس والشخصية</h3>\n                     <span className=\"text-[10px] text-[var(--accent)] bg-[var(--accent)]/10 px-2 py-0.5 rounded-full border border-[var(--accent)]/20\">متوافق مع {activeFamily?.labelAR}</span>\n                   </div>", "                   <h3 className=\"font-medium mb-3\">الملابس والشخصية</h3>", 'badge')
rep("                     {filteredOutfits.map(o => <option key={o.id} value={o.id}>{o.labelAR}</option>)}", "                     {OUTFITS.map(o => <option key={o.id} value={o.id}>{o.labelAR}</option>)}", 'outfit list')

old_bg = "                     <div>\n                       <label className=\"text-[11px] text-[var(--text-muted)] block mb-1\">حركة الخلفية</label>\n                       <select value={state.backgroundDynamics ?? 'empty'} onChange={e => setState({...state, backgroundDynamics: e.target.value as BackgroundDynamics})} className=\"w-full bg-[var(--bg-main)] border border-[var(--border)] rounded-xl px-3 py-2 text-sm appearance-none focus-ring\">\n                         <option value=\"empty\">هادئة / فارغة</option>\n                         <option value=\"casual\">عابرون غير مبالين</option>\n                         <option value=\"busy\">مزدحمة وحركية</option>\n                       </select>\n                     </div>\n"
rep(old_bg, "", 'old background UI')

for forbidden in ['Dark rectangular eyeglasses visible in reference MUST be worn', 'male wearing dark rectangular eyeglasses']:
    if forbidden in text:
        raise SystemExit(f'Unconditional eyewear text remains: {forbidden}')

path.write_text(text)
